repos:
  - repo: local
    hooks:
      - id: blubracket
        name: BluBracket
        language: system
        entry: blubracket pre-commit
        stages:
          - commit
        verbose: true
        always_run: true
        pass_filenames: false
